service: eduza-backend-dev

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
  users:
    handler: dist/users/main.handler
    events:
      - http:
          method: ANY
          path: /users
  cognito:
    handler: dist/cognito/main.handler
    events:
      - cognitoUserPool:
          pool: project-e
          trigger: PreSignUp
          existing: true